### ISSUE TITLE
bug: could not find a matching session for this request on social auth

### ISSUE THREAD

**Issue by casoetan** [lrstanley/chix#35]
### 🌧 Describe the problem

I'm getting the following error on provider/auth callback

`Internal Server Error: could not find a matching session for this request` Looks like that's happening on this line

guser, err := gothic.CompleteUserAuth(w, gothic.GetContextWithProvider(r, chi.URLParam(r, "provider")))

I guess I'm missing some configuration for sessions/cookies

### ⛅ Expected behavior

Expected to get the user object when login completes

### 💠 Version: chix

v1.0.0

### 🖥 Version: Operating system

macos

### 🤝 Requirements

- [X] I believe the problem I'm facing is a bug, and is not intended behavior. [Post here if you're not sure](../discussions/new?category=q-a).
- [ ] I have confirmed that someone else has not [submitted a similar bug report](../labels/bug).

**Comment by lrstanley** [comment]
Can you provide a functioning example project which reproduces the issue? I am using this in two places currently w/o issue.

My personal site (e.g. frontend redirects to `https://liam.sh/-/auth/providers/github?next=https://liam.sh/admin`)

Initialization: https://github.com/lrstanley/liam.sh/blob/b5c9fadfde62a2239d7a38c4d255fe2732349f0c/cmd/httpserver/http.go#L40-L52
Mounting: https://github.com/lrstanley/liam.sh/blob/b5c9fadfde62a2239d7a38c4d255fe2732349f0c/cmd/httpserver/http.go#L120

Spectrograph (discord bot, frontend redirects to `https://spectrograph.app/-/auth/providers/discord?next=https://spectrograph.app/dashboard`)

Initialization: https://github.com/lrstanley/spectrograph/blob/dae085f4a6d19060ac0fd3c0693faaf6606ab11a/cmd/httpserver/http.go#L41-L54
Mounting: https://github.com/lrstanley/liam.sh/blob/b5c9fadfde62a2239d7a38c4d255fe2732349f0c/cmd/httpserver/http.go#L120

Note that the usage of `next=<URL>` is not required, it's just used to redirect back to a specific page after login. Don't have to mount to the same location either.
